services:
  - type: web
    name: platform-brawl-server
    env: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: pnpm install && pnpm --filter shared build && pnpm --filter server build
    startCommand: pnpm --filter server start
    envVars:
      - key: NODE_ENV
        value: production
